version: '1'

services:
  web:
    build: .
    image: test:llm
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "5000:5000"
    volumes:
      - Models:/root/src/2023/langchain_gordon_experiments


volumes:
  Models: